# dbtools

`dbtools` is a simple package, available for R and Python that allows you to query databases using Amazon Athena and obtain the S3 path of the query output.

## R

### Installation

Before installing `dbtools`, you first need to install and load `devtools` (or `remotes`) using the following code:

```{}
install.packages("devtools")
library(devtools)
```

You should also ensure that the following dependencies are installed and loaded:

*   `boto3` (Python, preinstalled)
*   `data.table` (R, version 1.11.8 or above)
*   `python` (System, preinstalled)
*   `readr` (R, preinstalled)
*   `reticulate` (R)
*   `s3tools` (R, preinstalled)

For more information on installing packages, see Section \@ref(installing-packages).

To install and the latest version of `dbtools`, run the following code:

```{}
devtools::install_github("moj_analytical_services/dbtools")
library(dbtools)
```

### Functions

`dbtools` contains two functions:

*   `read_sql`
*   `get_athena_query_response`

#### `read_sql`

`read_sql` submits a query to Amazon Athena and returns the output of the query as a tibble, dataframe or data.table. A tibble is returned by default, however, you can select another option using the `return_df_as` argument.



You can read more about the function by running the following in R:

```{}
help?dbtools::read_sql
```



#### `get_athena_query_response`

### Examples

## Python

### Installation

Before installing `pydbtools`, ensure that the following dependencies are installed and loaded:

*   `boto3` (Python, preinstalled)
*   `gluejobutils` (Python)
*   `numpy` (Python, preinstalled)
*   `pandas` (Python, preinstalled)
*   `s3fs` (Python)

For more information on installing packages, see Section \@ref(installing-packages).

### Functions

### Examples
